'use client';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });
import { ThemeContext } from "@/components/ThemeContext";
import { LoginContext } from "@/components/LoginContext";
import '/node_modules/bootstrap/scss/bootstrap.scss';
import '../../../custom.scss';
import "bootstrap-icons/font/bootstrap-icons.css";
import { useEffect } from "react";
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);
  const [theme, setTheme] = useState('light');
  const [isLogIn, setIsLogIn] = useState(false);

  return (
    <LoginContext.Provider value={{isLogIn, setIsLogIn}}>
      <html lang="en">
      
        <body className='container-fluid d-flex justify-content-center m-0 p-0 overflow-x-hidden'>

          {children}
   
        </body>
      </html>
    </LoginContext.Provider>
  );
}

{/* <ThemeContext.Provider value={{theme, toggleTheme:()=>setTheme(theme === 'light'?'dark':'light')}}></ThemeContext.Provider> */}