'use client';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });
import { ThemeContext } from "@/components/ThemeContext";
import '/node_modules/bootstrap/scss/bootstrap.scss';
// import 'bootstrap/dist/css/bootstrap.min.css';
// import '/node_modules/bootstrap/scss/bootstrap-utilities.scss';
import '../../custom.scss';
import "bootstrap-icons/font/bootstrap-icons.css";
// import 'bootstrap/dist/js/bootstrap.bundle.min.js';
import SideBar from '@/components/Side Bar/SideBar';
import './global.css';
import { useEffect } from "react";
// import styles from '../components/Side Bar/SideBar.module.scss';
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);
  const [theme, setTheme] = useState('light');
  return (
    <ThemeContext.Provider value={{theme, toggleTheme:()=>setTheme(theme === 'light'?'dark':'light')}}>
      <html lang="en">
        <body className='container-fluid d-flex justify-content-end mx-0 px-0 overflow-x-hidden'>
          <SideBar />
          {/* <div className="border border-black container p-0 m-0 h-100 bg-info w-auto position-sticky top-0 left-0">
            bye
          </div> */}
          {/* <div className="border border-black container p-0 m-0 h-100 bg-danger min-vw-100 d-flex">
            hello
          </div> */}
          <main className='container-xl container-xxl container-lg container-fluid-md container-fluid-sm container-fluid p-0 m-0 d-flex align-items-center justify-content-center vh-100 vw-100'>
            {children}
          </main>
   
        </body>
      </html>
    </ThemeContext.Provider>
  );
}
